# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "Hugo FixIt Blog"
baseURL = "https://hugo-fixit.github.io/hugo-fixit-starter1/"
theme = [
  "FixIt",
  "shortcode-docs-bookmark"
]
defaultContentLanguage = "ja"
languageCode = "ja-JP"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 5
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
